# .github/workflows/export-files.yml
name: Run GitHub Action on Subfolder

on:
  workflow_dispatch:
    inputs:
      subfolder:
        description: 'Path of subfolder to process'
        required: true
        type: string

jobs:
  run-subfolder-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Go to subfolder and run command
        run: |
          if [ -d "${{ github.event.inputs.subfolder }}" ]; then
            cd "${{ github.event.inputs.subfolder }}"
            echo "✅ Inside subfolder: $(pwd)"
            ls -la
          else
            echo "❌ Subfolder '${{ github.event.inputs.subfolder }}' not found"
            exit 1
          fi
