# .github/workflows/export-files.yml
name: Trigger from WorkAto

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-from-workato]
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Zip all files
        run: |
          cd Source
          zip -r ../../source.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: all-files-zip
          path: source.zip
